# Usar la imagen oficial de PHP 8.3 con Apache
FROM php:8.3-apache

# Instalar extensiones necesarias para Laravel
RUN apt-get update && apt-get install -y \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip \
    git \
    curl \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install pdo pdo_mysql gd mbstring exif pcntl bcmath opcache

# Habilitar el módulo de reescritura de Apache
RUN a2enmod rewrite

# Copiar el archivo de configuración del Virtual Host al contenedor
COPY ./laravel.conf /etc/apache2/sites-available/laravel.conf

# Habilitar el nuevo Virtual Host y deshabilitar el sitio por defecto
RUN a2ensite laravel.conf && a2dissite 000-default.conf

# Instalar Composer
COPY --from=composer:2.7 /usr/bin/composer /usr/bin/composer

# Establecer el usuario 'laravel' para evitar problemas de permisos
RUN useradd -m -d /home/laravel -s /bin/bash laravel
USER laravel

# Cambiar los permisos de las carpetas importantes
#RUN chown -R laravel:laravel /var/www/html

# Establecer el directorio de trabajo
WORKDIR /var/www/html

# Exponer el puerto 80
EXPOSE 80
